### ISSUE TITLE
plugin not working with cordova 9 and XCode10

### ISSUE THREAD

**Issue by jcohenar123** [apache/cordova-plugin-camera#444]
# Bug Report

I'm using ionic AppFlow and when trying to build a production package with iOS 10.1 I'm getting the following error:

```
Discovered saved plugin "cordova-plugin-camera". Adding it to the project
Installing "cordova-plugin-camera" for ios
Adding cordova-plugin-camera to package.json
Failed to restore plugin "cordova-plugin-camera" from config.xml. You might need to try adding it again. Error: Using "requireCordovaModule" to load non-cordova module "glob" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

```

## Problem

After reinstalling the plugin the error remains. Ionic team tells me this is due to plugin incompatibility with Cordova 9.

### What is expected to happen?

Build package creates successfully

### What does actually happen?

Build fails.

## Information
Failure arised after Ionic Appflow updated to cordova 9

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Gina\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.2.3

System:

   NodeJS : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
@jcohenar123 Can you provide what version of the plugin you are using? 

In the current release `4.0.3`, the usage of `requireCordovaModule` does not exist.

I am suspecting that either,
a) you have a very old plugin that may use `requireCordovaModule`.
b) the error message your showing isn't accurate and could be related to another plugin. (timing)
c) the tooling (Ionic AppFlow) could be using `requireCordovaModule`.

**Comment by jcohenar123** [comment]
Running cordova plugin ls gives me the following list:

cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-qrscanner 3.0.1 "QRScanner"

As you can see we are using version 4.0.3 (a). Appflow is supposed to be
using Cordova 9 which doesn't use requireCordovaModule anymore (confirmed
this with Ionic team) so it must be (2) based on your reasoning. However I
have been unable to identify the problematic plugin. What did work for me
was to install the script detailed here
https://ionic.zendesk.com/hc/en-us/articles/360000160067-Adding-execute-permissions-using-git

thanks!

**Comment by erisu** [comment]
I think your problem is in these plugins:

`cordova-plugin-add-swift-support@1.7.2`
https://github.com/akofman/cordova-plugin-add-swift-support/blob/1.7.2/add-swift-support.js#L12755
https://github.com/akofman/cordova-plugin-add-swift-support/blob/1.7.2/add-swift-support.js#L12895
https://github.com/akofman/cordova-plugin-add-swift-support/blob/1.7.2/add-swift-support.js#L12908
https://github.com/akofman/cordova-plugin-add-swift-support/blob/1.7.2/add-swift-support.js#L12921

and also if Windows builds `cordova-plugin-qrscanner`
https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/hooks/windows/check-arch.js#L5
https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/hooks/windows/check-arch.js#L6

You will need to ask these plugin developers to update and remove this usage if they have not already done so in a newer release.

Also as a side note, the latest iOS platform has improved swift support. You might not need that plugin anymore. Please take a look at the docs as well as https://github.com/apache/cordova-discuss/blob/master/proposals/ios-swift-plugin-support.md

I will close out this ticket as this issue is not related to this plugin.
