### ISSUE TITLE
Loader to know when DATA_URL finishes

### ISSUE THREAD

**Issue by eeerrrttty** [apache/cordova-plugin-camera#459]
The base64 return from DATA_URL usually takes a lot of time. 

It's usefull to user experience to know when 'data_url' starts loading and when it finishes.

But, how this is an internal code from plugin, i would sugest the possibility to pass this parameter as option "DATA_URL started loading", "DATA_URL finished loading"

**Comment by thevirajshelke** [comment]
A loader would be really great! I am facing a similar issue, especially when the image quality is 100 (These days the size of images is too big, so takes time for processing).

**Comment by jcesarmobile** [comment]
can you elaborate? it's not clear what you are asking

**Comment by breautek** [comment]
I would vote no on adding a loader for `DATA_URL` destinations and here's why.

Using `DATA_URL` encodes the binary image data to base64, and on phones, especially modern ones, these images are very high resolution, and even with jpeg encoding these images are fairly large to begin with. Base64 encoding will expand that size significantly (by about 40%).

This consumes a lot of memory in the javascript engine as a string, which isn't really optimised that kind of usage in a single variable, and that is where you are seeing the slowdown. This is particularly dangerous on low budget phones where ram is very limited. See the note in the docs:

>NOTE: Photo resolution on newer devices is quite good. Photos selected from the device's gallery are not downscaled to a lower quality, even if a quality parameter is specified. To avoid common memory problems, set Camera.destinationType to FILE_URI rather than DATA_URL.

JavaScript is single threaded, so during the time it takes to encode the image, everything will be locked down and paused until either the JS completes encoding, or it fails to allocate memory due to insufficient RAM.

I would recommend using a `FILE_URI` destination instead. When saving to a file, you'll get a file path instead. Then you can simply move the file from its temporary location to its proper location. You can also use the file reading APIs to read the data into a `Blob`. The proper javascript object type to represent binary data, including images. From a blob, you can create object urls that can be used inside the `<img>` tag, or you can send the blob itself to a server using the `XMLHttpRequest`. All of this is far more efficient on both CPU processing power and memory than encoding a base64 representation.

`DATA_URL` is definitely simpler to use, and but it is major drawbacks. It might have made more sense 5-6 years ago, but modern day it has aged. This might be an unpopular opinion, but In my opinion, the `DATA_URL` destination should be deprecated.

**Comment by jcesarmobile** [comment]
closing since there was no response
