### ISSUE TITLE
navigator.camera is undefined with wkwebview

### ISSUE THREAD

**Issue by corrrso** [apache/cordova-plugin-camera#502]
Hi

### What is expected to happen?
I just updated my webview thanks to wkwebview. The application's performances drastically improved and so is the webview management of CSS. Anyway, all of the plugins that are using any kind of sensors are failing (apart from geolocation, that is working).

### What does actually happen?
Not only navigator.camera, but also navigator.device (cordova-plugin-mediacapture) and cordova (cordova.plugin.barcodescanner.scan for phonegap plugin barcodescanner) are undefined for some reason. If i remove the webview, everything comes back to normal. In particular, "navigator" is a valid variable, but it doesn't contain the "camera" object.
![image](https://user-images.githubusercontent.com/23524581/65015684-7ebde380-d922-11e9-954c-bca49fd6f3aa.png)

## Information
All you should need is to create a cordova app with the latest cordova CLI installed, an iOS 5.0.1 platform. After that you need to install cordova-plugin-wkwebview-engine and cordova-plugin-camera.

### Command or Code
You just need to use the navigator.camera.getPicture function

### Environment, Platform, Device
i'm creating the project by using the latest cordova CLI and ios 5.0.1 platform. To compile I am using the latest version of XCode and i am using an iPad 2018 updated to iOS 12.4.1 to do the testing.

### Version information
Cordova: CLI 9.0.0, platform: iOS 5.0.1, the plugin list is in the image below
Other Frameworks: none
Operating system: OS X 10.14.6 , Xcode: 10

![image](https://user-images.githubusercontent.com/23524581/64974822-e0903600-d8ad-11e9-9747-33a53137960d.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by corrrso** [comment]
Hi @timbru31, i am sorry but I was in a bit of a hurry (and still am, i must resolve this problem asap). I edited the post by following the template.

**Comment by corrrso** [comment]
Hi again. I managed to resolve the problem. Somehow, my first attempt to remove all of the plugins and the platform to readd them didn't work. Then I tried to redo the project from scratches, but this still didn't work. I had to remove the application's cache from the ios settings to make everything work again. Maybe the change of webview misunderstands something contained inside the cache, even tho I don't know what.

Thank you anyway for your attention!

**Comment by vinnichase** [comment]
I have the exact same problem with all the same versions. Removing and readding all plugins with deleting the application cache didn't help. The only thing I didn't try so far, was rebuilding the application from scratch. Do you maybe have another advice?

**Comment by vinnichase** [comment]
@corrrso can you verify that you made camera and media-capture working on WKWebView without any additional RTC implementation? By my current information, WKWebView is not exposing any of these APIs natively which should make it impossible.

**Comment by corrrso** [comment]
Hi @vinnichase . I confirm to you that by making a new project from scratches, everything went fine without touching a single line of code. WkWebView doesn't expose the APIs, but that's exactly what cordova is for. Cordova is like a bridge between a web environment and the native device environment. That's why the fact that we are using WkWebView is not important at all. I never had this issue again since september, so you should do just fine by making a project from scratches. Try to update your cordova and make a project by using the latest ios platform available. Then just add the WkWebView and the camera plugin, just to verify that everything works just fine.

**Comment by vinnichase** [comment]
@corrrso thanks for your reply even if this problem is not yours anymore. OK I created a new cordova app with cordova 9.0.0. Those are my plugin versions (newer than in your example):
```JSON
{
   "cordova-ios": "^5.1.1",
   "cordova-plugin-camera": "^4.1.0",
   "cordova-plugin-wkwebview-engine": "^1.2.1"
}
```
I cleared the application cache and ran it on my iPhone X physical device. Its a plain react application. It renders correctly but `navigator.camera` stays `undefined`. However the `deviceready` event is not fired neither in my main app nor in the from scratch test app. I think both problems are related.

Would you mind sharing your code for your from scratch app (older versions are fine for me)? I'm also open for chat in discord (VinniChase#9406) and share the final outcome later on here.

Tanks so far!

**Comment by breautek** [comment]
> However the deviceready event is not fired neither in my main app nor in the from scratch test app. I think both problems are related.

Definitely related. `deviceready` tells you when the plugin apis are ready to be used. If it's not firing there is some other issue going on preventing the init process from completing. 

First I would ensure that the `cordova.js` file is being loaded in. You should have a `<script type="text/javascript" src="cordova.js"></script>` in your html file. The cordova.js file is provided behind the scenes. You can verify that this file is being loaded in successful by using the safari remote inspector, then refreshing the app webview (cmd+r while the inspector is in focus). Then look at the network tab for the javascript files being loaded in.

After you confirm the `cordova.js` file is being loaded in successfully, then in my experience, this is usually something on the native side. You may need to run the app with Xcode so that you can attach the xcode debugger to see the native console logs to get more insight of what might be happening.

**Comment by corrrso** [comment]
I confirm everything @breautek says. If your deviceready is not triggered, you should definitely take care about that first.

**Comment by vinnichase** [comment]
Thanks that was a very good hint! I'm on it. I will share my outcome soon.

**Comment by vinnichase** [comment]
OK! Finally resolved it. I indeed removed `<script type="text/javascript" src="cordova.js"></script>` from my index.html for the migration to `WKWebView` and completely forgot about it. I had to remove it, because I always got a white screen since I was migrating a relatively big app. Key to resolve the white screen was:

```Bash
$ cordova plugin add cordova-plugin-wkwebviewxhrfix
```

Otherwise nothing is loaded in the web view. That I just learned seconds ago. If you still encounter a white screen you have to remove `ios.json` from the plugins folder and remove and readd the ios platform:

```Bash
$ cordova platform remove ios
$ cordova platform add ios@5.1.1
```
> 5.1.1 in my case!

It is by far not trivial to overlook all possible problems at once while copying over files and starting projects from scratch to isolate problems. Basic things like `cordova.js` can quickly be overseen. So I hope I can help anyone else who might run into similar problems or fighting against themselves stupidly as I did.
