### ISSUE TITLE
Edit mode for selected image

### ISSUE THREAD

**Issue by JDonadio** [apache/cordova-plugin-camera#636]
# Feature Request

## Motivation Behind Feature
Actually the edittion mode is **only** available for images taken from the camera but not for the selected one from the photo library.

## Feature Description
Ability to use the edition mode of this plugin on both modes: take and browse.

## Alternatives or Workarounds
For now I'm using [Cropper.js](https://github.com/Mawi137/ngx-image-cropper) but the performance is really laggy for large images if you need to rotate or flip the canvas.

Thank you Sr !

**Comment by jcesarmobile** [comment]
In which platform are you seeing this?
Can you provide a sample app or sample code?

**Comment by JDonadio** [comment]
I'm trying on a OnePlus 3T with Android 9.

You can check this out to reproduce the behavior:

https://github.com/JDonadio/ionic-camera

Let me know if you need more info. Thanks in advance!

**Comment by breautek** [comment]
The existing `allowEdit` has problems on android which is well documented and won't be addressed.

I don't foresee support for adding editing features since that also seems out of scope for the plugin responsibilities. If performance is a concern, a third-party plugin can probably implement editing features.

But JS implementations using a canvas should be plausible too.
