### ISSUE TITLE
copile problem  Task :app:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by zoranmil** [apache/cordova-plugin-camera#726]
# Bug Report

## Problem
on android 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

### What is expected to happen?
plugins
 "prepare_queue": {
    "installed": [],
    "uninstalled": []
  },
  "config_munge": {
    "files": {}
  },
  "installed_plugins": {
    "cordova-plugin-camera": {
      "ANDROID_SUPPORT_V4_VERSION": "27.+",
      "PACKAGE_NAME": "com.nav.navidiku"
    },
    "cordova-plugin-file": {
      "PACKAGE_NAME": "com.nav.navidiku"
    },
    "cordova-plugin-splashscreen": {
      "PACKAGE_NAME": "com.nav.navidiku"
    },
    "cordova-plugin-whitelist": {
      "PACKAGE_NAME": "com.nav.navidiku"
    },
    "es6-promise-plugin": {
      "PACKAGE_NAME": "com.nav.navidiku"
    }
  },
  "dependent_plugins": {}
} 

### Command or Code

build realise apc

### Environment, Platform, Device

Windows android studio

## Checklist

- [] I searched for existing GitHub issues
- [] I updated all Cordova tooling to most recent version
- [] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Can you provide the actual error?
That only means Java failed to compile, but should also say why and that’s the important part.

**Comment by WilcoVertegaal** [comment]
I think I ran into this issue, so I'll provide the error messages:

`line 40: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;

line 303: error: cannot find symbol
        this.imageUri = new CordovaUri(FileProvider.getUriForFile(cordova.getActivity(),`

and that error line on line 801.

I think it is related to Android 4 being deprecated in Cordova Android 10 - if I understood all of this correctly?

**Comment by jcesarmobile** [comment]
That error is because you are using AndroidX dependencies and the plugin doesn't support AndroidX yet (because cordova-android wasn't using it by default neither)
Now that cordova-android 10 is out with AndroidX enabled, it will be fixed in https://github.com/apache/cordova-plugin-camera/pull/751

Also, as workaround, you can use tools such as jetifier, or cordova-plugin-androidx-adapter or similar tooling that patches the plugins to use AndroidX

Closing since the issue creator didn't provide any information
