### ISSUE TITLE
Camera doesn't work after building final release in ionic 5

### ISSUE THREAD

**Issue by kennedyngigi4** [apache/cordova-plugin-camera#742]
This is my experience;
1. ionic cordova build android;
    After generating the apk I can comfortably use Camera even though it doesn't support "allowEdit"

2. ionic cordova build --prod --release
    After generating the apk signing and zip-aligning I uploaded the app to play store. Unfortunately most of my users complained about the camera failure. I also tested with Android 8, 10 devices and 100% failure. 

Any helpon how I can solve this please? Its urgent.

**Comment by breautek** [comment]
`allowEdit` cannot reliably be used on android. See [Android Quirks](https://github.com/apache/cordova-plugin-camera#android-quirks-1)

> allowEdit is unpredictable on Android and it should not be used! The Android implementation of this plugin tries to find and use an application on the user's device to do image cropping. The plugin has no control over what application the user selects to perform the image cropping and it is very possible that the user could choose an incompatible option and cause the plugin to fail. This sometimes works because most devices come with an application that handles cropping in a way that is compatible with this plugin (Google Photos), but it is unwise to rely on that being the case. If image editing is essential to your application, consider seeking a third party library or plugin that provides its own image editing utility for a more robust solution.

Just because it works for you, doesn't mean it will work for your users. It all depends on the device and it's configuration.

**Comment by kennedyngigi4** [comment]
Hello, my case as described in the title is that the camera functionality fails when I build the final release.

**Comment by breautek** [comment]
My apologies but with such little information provided it isn't clear what the actual issue is.

Here are some things that can help understand/isolate the issue:
- Ensure you're using the most recent release versions of the platforms, plugins and CLI tools, etc. (Note that Cordova doesn't officially support Node 16 yet, I would recommend using the latest Node 14 release)
- Ensure that your Android Studio SDK tools are up to date (Recommended build tools version 29, API platform 29)
- If you're zip aligning / signing manually, ensure you're signing with all schemes for maximum compatibilty. You can can read more on [Android Signing Schemes](https://source.android.com/security/apksigning). Alternatively, you can let Cordova sign your app for you by utilizing the [build.json file](https://cordova.apache.org/docs/en/10.x/guide/platforms/android/index.html#using-buildjson).
- Build an isolated reproduction test app without ionic or any frameworks, include only what is necessary to reproduce the issue. [Learn more about creating reproduction test apps](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)

If the above steps doesn't solve your issue, then at the very least should allow you to provide a more detailed bug report. **Please do follow the Issue form provided in the textarea when you create the issue as it required critical information that allows us to simulate your environment to hopefully reproduce your issue.**

Kind regards,
