### ISSUE TITLE
Camera wont open on OnePlus 7T.

### ISSUE THREAD

**Issue by PhilBouvet** [apache/cordova-plugin-camera#776]
# Bug Report

## Problem
Camera wont open on OnePlus 7T. Works as intended on every other device we have tested with, including emulators.

Do you guys have any solution for me? Or tips as to what I can do next to try to resolve this problem?

### What is expected to happen?
Camera opens, and pictures can be taken.

### What does actually happen?
Nothing happens.

## Information
Screenshots from debugging:

![image](https://user-images.githubusercontent.com/32924585/141274581-2977eeac-6357-42da-9e5c-8c569d9926f5.png)
![image](https://user-images.githubusercontent.com/32924585/141277467-07538d24-9cb9-461e-971c-7784bd32f20d.png)
=> msgs = undefined

Short explanation:
I get into the exec function, when running the line with msgs = nativeaApiProvider... It ends up not returning anything. Resulting in that msgs = undefined, and nothing more happens from that function.

Neither success, nor fail, callback functions are invoked.

### Command or Code
```
navigator.camera.getPicture(onSuccess, onFail, {
        quality: 20,
        correctOrientation: true,
        destinationType: navigator.camera.DestinationType.DATA_URL,
        saveToPhotoAlbum: true,
});
```

The only custom xml-field for android:
```
<platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:usesCleartextTraffic="true"/>
        </edit-config>
</platform>
```

### Environment, Platform, Device
Phone: OnePlus 7T
OS: Android 11

### Version information
From package.json:

Cordova ^9.0.0
cordova-plugin-camera ^6.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by PhilBouvet** [comment]
bump

**Comment by igorsantos07** [comment]
It was driving me nuts when I checked the whole docs twice looking for ANY hint on what could I be missing, since the Gallery action worked great (after a couple of patches, since....... the DATA_URL isn't a URL but a crude base64? lol).

Then I decided to dig into the issues and discovered THIS ONE. That's exactly my device.
I mean.... what the hell? And also, Android fragmentation is an issue up to this day?

And lastly: this plugin seems abandoned, if not Cordova as a whole. For good. I'm resorting to this plugin ONLY because [cordova-android can't properly handle the `capture` optionS in a file input](https://github.com/apache/cordova-android/issues/816).

Wish you all best of luck.

**Comment by igorsantos07** [comment]
The partial solution here _might_ be helpful? https://github.com/apache/cordova-plugin-camera/issues/763

**Comment by igorsantos07** [comment]
This seems solved on cordova-android 12 :pray:

**Comment by breautek** [comment]
stale (v8 will have significant improvements on error feedback)
