### ISSUE TITLE
Selected photos picker when user chooses select photos permission on iOS 14 and above

### ISSUE THREAD

**Issue by dcxn** [apache/cordova-plugin-camera#805]
# Feature Request

## Motivation Behind Feature
When using the camera plugin on iOS in combination with `cordova.plugins.diagnostic` to request camera permissions as mandated by the platform, the camera plugin does not seem to differentiate between the regular `Allow Access to All Photos` and the new `Select photos` permission added in iOS 14. It always opens the camera roll and shows / allows selecting from all photos.

Note: I've searched a while for info about this feature but have not found it, either in plugin docs or open/closed issues. 

## Feature Description
Introduced in iOS 14. Gives user the option to only allow an app access to selected photos, which the user can then select from (instead of the full camera roll). [Article describing the feature](https://www.techrepublic.com/article/how-to-use-the-limited-photos-picker-in-ios-14-for-added-privacy/).

## Alternatives or Workarounds
None that I know of at this moment.

**Comment by jcesarmobile** [comment]
The picker provided by Apple doesn't allow to filter and show only the images that the user selected, it always shows all and that's what we use.
When the user select `Select photos` instead of `Allow Access to All Photos`, the library permission is limited instead of granted. Limited means the access to the photo info is limited (i.e. you can't get the photo exif), but you can still get a copy of the photo, which is what the plugin returns.

**Comment by jcesarmobile** [comment]
yeah, those are custom pickers, there is a native API to get all the limited photos and you can use that to present a custom picker to the user, but you have to build the picker UI
