### ISSUE TITLE
Support for Android api 33

### ISSUE THREAD

**Issue by ohtanzcom** [apache/cordova-plugin-camera#825]
# Feature Request

## Motivation Behind Feature

READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE used in CameraLauncher.java from API 33 are no longer available.
Instead, fine-grained permission controls such as READ_MEDIA_IMAGES are required.

https://developer.android.com/about/versions/13/behavior-changes-13

## Feature Description

READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE always return denied, so these need to be corrected.

**Comment by breautek** [comment]
We do have a PR https://github.com/apache/cordova-plugin-camera/pull/814 for this, but is ultimately waiting on the next major release of cordova-android for API 33 support, so that we can use the newer permissions.

However you can likely test the PR today with cordova-android@11 by using the following preferences:

```
<preference name="android-buildToolsVersion" value="33.0.0" />
<preference name="android-compileSdkVersion" value="33" />
```

You'll also need use Android's SDK Manager to install API 33 platform and Android 33 Build Tools. You may also need to update your `PATH` environment variable to include `$ANDROID_HOME/build-tools/33.0.0/`, replacing `32.0.0` if present.

I however am not sure if cordova-android@11 will build on API 33 without further changes.

**Comment by ohtanzcom** [comment]
I am using API33 on cordova10 and was unable to get the photo taken by the activated camera and got an error, so I commented the part of the screenshot and forced it to work around the permission error.
![2023-03-01 10_47_23-Clipboard](https://user-images.githubusercontent.com/69287535/222023741-6374fc14-2221-45e5-aebb-a512e7ff3578.png)

**Comment by jkenjarCR** [comment]
> We do have a PR #814 for this, but is ultimately waiting on the next major release of cordova-android for API 33 support, so that we can use the newer permissions.
> 
> However you can likely test the PR today with cordova-android@11 by using the following preferences:
> 
> ```
> <preference name="android-buildToolsVersion" value="33.0.0" />
> <preference name="android-compileSdkVersion" value="33" />
> ```
> 
> You'll also need use Android's SDK Manager to install API 33 platform and Android 33 Build Tools. You may also need to update your `PATH` environment variable to include `$ANDROID_HOME/build-tools/33.0.0/`, replacing `32.0.0` if present.
> 
> I however am not sure if cordova-android@11 will build on API 33 without further changes.

how do i install the PR? kind of important information is it not?

**Comment by ryward2331** [comment]
Android 12 is out any update?
https://www.npmjs.com/package/cordova-android

**Comment by scotthmusson** [comment]
Now that Cordova Android 12 is out can we expect the fix for this to be released soon?  Any ETA on this release?  Appreciate your help!

**Comment by brunoalex** [comment]
we need this fix

**Comment by alexisGandar** [comment]
+1 need the fix

**Comment by sonikdesign** [comment]
+1 need the fix please

**Comment by Sotatek-HaiNguyen3** [comment]
May I ask why you can't merge pull request #814 , is there any problem?
Do you have any plans to merge this pull request?
