### ISSUE TITLE
Error Code 20 on Android

### ISSUE THREAD

**Issue by jkenjarCR** [apache/cordova-plugin-camera#826]
# Bug Report

### What does actually [happen?]([url](url))
![Screenshot_20230228-112443](https://user-images.githubusercontent.com/79476660/221987749-c4386a4e-de66-49ca-9f3a-233df79038c1.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Please edit the post and provide the requested information in the form. Definitely include code snippets and version information.

**Comment by prabusharan** [comment]
![image](https://user-images.githubusercontent.com/35057652/229412311-aa71b801-d56f-4146-bf54-308d9c3269db.png)

Good Morning @breautek,

The same issue occurs in android 11 "Camera issue:20" to unable open the camera. Below I include the AndroidManifest.xml file for your reference. can you please help me to resolve this issue

`<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="50100" android:versionName="5.1" package="com.test.app" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:networkSecurityConfig="@xml/network_security_config" android:requestLegacyExternalStorage="true" android:supportsRtl="true" android:usesCleartextTraffic="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:exported="true" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@style/Theme.App.SplashScreen" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.cordova.plugin.camera.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>
        <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />
        <service android:exported="false" android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />
        <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />
        <meta-data android:name="firebase_analytics_collection_enabled" android:value="true" />
        <meta-data android:name="firebase_performance_collection_enabled" android:value="true" />
        <meta-data android:name="firebase_crashlytics_collection_enabled" android:value="true" />
        <meta-data android:name="firebase_messaging_auto_init_enabled" android:value="true" />
        <service android:name="cordova.plugin.floatview.MyService" />
    </application>
    <uses-permission android:name="android.hardware.location" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
    <uses-permission android:maxSdkVersion="29" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:maxSdkVersion="32" android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" />
        </intent>
        <intent>
            <action android:name="com.android.camera.action.CROP" />
            <data android:mimeType="image/*" android:scheme="content" />
        </intent>
    </queries>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-feature android:name="android.hardware.location.gps" android:required="true" />
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-feature android:name="android.hardware.telephony" android:required="false" />
</manifest>
`

**Comment by AndrWeisR** [comment]
Same error here. Here's my code. I'm upgrading my Ionic app (where selecting a photo from the gallery previously worked) to support API 33, using Cordova 12.0.0. I upgraded the camera plugin to 6.0.0, but still get error 20.

```
    const options: CameraOptions = {
      mediaType: this.camera.MediaType.PICTURE,
      correctOrientation: true,
      targetWidth: 1024,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      destinationType: this.camera.DestinationType.FILE_URI
    };

    this.camera.getPicture(options).then((imageData) => {
        ....
    }, (err) => {
      console.log(err); <== This outputs "20".
    });
```

**Comment by epetre** [comment]
Getting the same issue with the README.md example 

```
navigator.camera.getPicture(onSuccess, onFail, { quality: 50,
    destinationType: Camera.DestinationType.FILE_URI });

function onSuccess(imageURI) {
    var image = document.getElementById('myImage');
    image.src = imageURI;
}

function onFail(message) {
    alert('Failed because: ' + message);
}
```

I think code 20 must is probably related to permissions. 
It's probably going to be covered by 

https://github.com/apache/cordova-plugin-camera/pull/814

**Comment by levieu** [comment]
To fix the problem you can use the following [fork](https://github.com/levieu/cordova-plugin-camera.git). The 'Error code 20' problem is due to the failure to request the READ_MEDIA_IMAGES permission; this permission was introduced by android starting from api level 33 [link](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE)

**Comment by epetre** [comment]
Thx.
I tried this your fork and it didn't work for me, the camera hangs too.
But from what I saw, the changes you have there are covered in this PR too aren't they?

**Comment by brunoalex** [comment]
same problem

**Comment by jimbergman** [comment]
I'm experiencing the same issue.

Running `cordova@12.0.0` (command line tools)
these settings don't work with the camera plugin:
`<preference name="android-targetSdkVersion" value="33" />`
`<engine name="android" spec="12.0.0" />`

it works fine rolling back to these settings:
`<preference name="android-targetSdkVersion" value="32" />`
`<engine name="android" spec="11.0.0" />`

changing the targetSdk to 32 without also setting android to 11 throws an error at build

the ticking clock here is Google's targetSdk 33 requirement starting on Aug 31, 2023
[https://developer.android.com/google/play/requirements/target-sdk](https://developer.android.com/google/play/requirements/target-sdk)

**Comment by cyril23** [comment]
> EDIT: the fork by levieu above did not work for me

same here for me. Testing on Android 13.0.0 on a OnePlus 9 Pro:

I've tried the following repos **and finally found a working one**:
- `apache`:
  - current Master https://github.com/apache/cordova-plugin-camera (which includes https://github.com/apache/cordova-plugin-camera/commit/23642f09b5e72d38bce171041f260674ba297c0e - which is obviously NOT related to THIS issue)
  - result: Error 20
- fork `OutSystems`:
  - I actually came here googling for the error 20 issue, and at first found this discussion https://www.outsystems.com/forums/discussion/86980/cordova-camera-plugin-returning-error-20/ so I gave the `OutSystems` fork a try
  - release https://github.com/OutSystems/cordova-plugin-camera/releases/tag/4.2.0-OS42 (via `plugin name="cordova-plugin-camera" spec="https://github.com/OutSystems/cordova-plugin-camera.git#4.2.0-OS42" />`)
  - result: various Build errors (`Failed to install 'cordova-plugin-camera': Error: pod: Command failed with exit code 1` in `node_modules/cordova-common/src/superspawn.js:136:25`, even after increasing my `<preference name="android-minSdkVersion" value="22" />` to `<preference name="android-minSdkVersion" value="26" />` which only the `OutSystems` fork needs apparently!)
- fork `levieu`:
  - current Master https://github.com/levieu/cordova-plugin-camera (which contains https://github.com/levieu/cordova-plugin-camera/commit/06186bc150fe56f8a9adb40a8393dca1298e50f8 which looked promising)
  - result: Error 20 still
- fork `jalios`
  - current Master https://github.com/jalios/cordova-plugin-camera/ (which contains https://github.com/jalios/cordova-plugin-camera/commit/bd1dd6a742bafc63591169eb371e39ad63007d97 which looks promising, too)
  - result: **OK, finally I can take pictures again**!

So I've solved the Issue for me by including
`<plugin name="cordova-plugin-camera" spec="https://github.com/jalios/cordova-plugin-camera.git" />`
instead of
`<plugin name="cordova-plugin-camera" spec="6.0.0" />`

**Comment by epetre** [comment]
@cyril23  🔥 🙌 

It also works on my Samsung S20, with Cordova 12, Android 13 API 33.

**Comment by cyril23** [comment]
> Thx @cyril23 🔥 🙌
> 
> It also works on my Samsung S20, with Cordova 12, Android 13 API 33.

glad to hear, but the https://github.com/jalios/cordova-plugin-camera/ fork still has some problems on **an old X10302 tablet running Android 7.0.0.** On that Android 7 device it is **not the error 20** though:
![image](https://github.com/apache/cordova-plugin-camera/assets/5645872/f1a1fb78-4de6-412d-bb8c-bb80e117d663)
- so on this Android 7 device I get an error `Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=7790, uid=10046 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()`
- In order to take pictures on the Android 7 within my app, I **needed to manually set the storage permission** within Settings -> Apps -> (my app) -> permissions. 
- The "camera" setting has been requested successfully by the plugin, but the "storage" permission apparently hasn't been requested correctly by the plugin, so I had to allow it myself manually. (This is probably caused because my app crashed when starting the camera for the first time and requesting permissions for the first time. During the crash apparently only the "camera" permission has been set successfully - and the "storage" permission not.)
- On the [Apache 6.0.0 Version](https://github.com/apache/cordova-plugin-camera/releases/tag/6.0.0) the plugin requests two permissions, both camera and storage permissions, and therefore the Apache 6.0.0 works without a problem on this old Android 7.0.0 device. But the Apache 6.0.0 version of course has the error 20 problem on Android 13 phones, so there is that.
- Anyhow: If the user is lucky and has already allowed the external storage successfully (e.g. via an old app using the Apache 6.0.0 version), and only gets an update of the app via Play Store, the camera can be used without a problem.

The same storage permission problem exists on Android 8.1.0 too, on an old Nexus 5X (LG H791).
In all cases, no error "20" though.

**Comment by matheus-inacio** [comment]
I've created an app from zero and ran on an emulator with android 13, i was getting this error as well.

Oddly enough, if i keep pressing the camera button multiples times really fast, it eventually opens the camera app (?!?) 😕

**Comment by DaedalusDev** [comment]
@cyril23 Here a fork inspired from the work of @jalios. Work perfectly on Android 13, 7 and 8 :tada:

I've only change that rows to match original code :
```diff
-        boolean saveAlbumPermission;
-        if (this.saveToPhotoAlbum) {
-            saveAlbumPermission = hasPermissions(storagePermissions);
-        } else {
-            saveAlbumPermission = true;
-        }
+        boolean saveAlbumPermission = hasPermissions(storagePermissions);
```

**Comment by FrancescoPaiola** [comment]
I'm using ionic 6 (capacitor 5).
As mentioned by @cyril23 the jalios [fork](https://github.com/jalios/cordova-plugin-camera) worked for me (the fix is [here](https://github.com/jalios/cordova-plugin-camera/commit/bd1dd6a742bafc63591169eb371e39ad63007d97)).
To that follow these steps:
```
// uninstall cordova-plugin-camera
npm uninstall cordova-plugin-camera 
// install jalios fork
npm i https://github.com/jalios/cordova-plugin-camera.git
// if it's not already installed
npm install @awesome-cordova-plugins/camera 
ionic cap sync
```

**Comment by arne-diegenbach** [comment]
Using Cordova the jalios branch works fine under Android 12 and 13 (didn't test others).
I believe Apache should merge this into the main branch urgently as of next month targeting SDK 33 is required for Android / Google PlayStore. Thanks all for the community effort to solve this.

**Comment by cyril23** [comment]
> @cyril23 Here a fork inspired from the work of https://github.com/jalios. Work perfectly on Android 13, 7 and 8 🎉
> 
> https://github.com/DaedalusDev/cordova-plugin-camera/

**Thanks a lot** for your work! I've tested it, too on the following the devices - **everything works perfectly**:
- Android 7.0, Medion LifeTab X10302 (the only tablet in my tests)
- Android 7.1.2, Zebra TC 25
- Android 8.0.0, Samsung Galaxy S7
- Android 8.1.0, Nexus 5X (LG H791)
- Android 11, Newland NFT 10
- Android 13, OnePlus 9 Pro
- Android 13, Pixel 7
- (iOS 16.5.1, iPhone 11 Pro)

> Using Cordova the jalios branch works fine under Android 12 and 13 (didn't test others).
I believe Apache should merge this into the main branch urgently as of next month targeting SDK 33 is required for Android / Google PlayStore. Thanks all for the community effort to solve this.

yes, but I would recommend DaedalusDev' Branch on https://github.com/DaedalusDev/cordova-plugin-camera/ (I mean his merge request) because of its Android 7-8 downwards compability.

**Comment by nicholaszuccarelli** [comment]
I've followed the above steps for switching to the Daedalus branch and it is still not working for me. Using s22 Ultra on Android 13 and OneUI 5.1

**Comment by nicholaszuccarelli** [comment]
+1 this is great. Need it merged!

**Comment by FlossyWeb** [comment]
+1 would be cool to merge, thanks for the fix.

**Comment by vladretca** [comment]
+1 if you can prioritize this

**Comment by arne-diegenbach** [comment]
Please merge ASAP.

**Comment by TomPretorius** [comment]
I have tried ALL of these and still getting error 20 with API level 33

**Comment by bonjourjoel** [comment]
I get an error 20 even by granting successfully the permission READ_MEDIA_IMAGES. It's on an emulator with Android SDK 33.

Anyone knows which permission is required to remove error code 20?
Or how to know what error code 20 means exactly in this situation, because it's not very accurate and i don't know where to go from here?

**Comment by LucasBourgeois** [comment]
@TomPretorius check that ure really using the fork instead of the apache release.

Yet, time limit is tomorrow and still no release of this fix... u can ask to google to delay the restriction a little bit (by 4 months if i remember right) and just have to wait the release of the fix..

Please consider to resolve and release a fix of this fast

**Comment by dovh-me** [comment]
> I have tried ALL of these and still getting error 20 with API level 33

Make sure you remove the existing cordova-plugin-camera before you install the mentioned one.
`cordova plugin uninstall cordova-plugin-camera`
`cordova plugin add https://github.com/jalios/cordova-plugin-camera.git`

Thanks @cyril23 for the fix 😍

**Comment by breautek** [comment]
Should be fixed by https://github.com/apache/cordova-plugin-camera/pull/844

**Comment by codingwithashu** [comment]
@cyril23   error is gone  but the new error came "no image selected", 
after taking the image click on the check icon, this error came


https://github.com/apache/cordova-plugin-camera/assets/111554315/60b1a06a-9daa-4494-9a22-04d6fcc34de6

**Comment by priyambadaBestinet** [comment]
not working with https://github.com/jalios/cordova-plugin-camera.git ,  camera not opening now.

**Comment by vikrantttriazinesoft** [comment]
1) git clone https://github.com/apache/cordova-plugin-camera.git
2) open the cordova-plugin-camera directory in any code editor
3) search the cordova-android in project and then change cordova-android value to the version which is greater than yours cordova-android version used by you in your current project
4) then install the plugin using :-  cordova plugin add ./path_to cordova-plugin-camera ( directory )
5) then run prepare command 
6) add <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" /> in androidmanifest file
7) add this in application tag of manifest file
     android:largeHeap="true" android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true"

8) that's it 
9) now u can use the camera in ur cordova application

**Comment by vikrantttriazinesoft** [comment]
if u want to shift ur project to cordova-android 12
then the solution is 
1 ionic cordova platform rm android
2 ionic cordova plugin rm cordova-plugin-camera
3 ionic cordova platform add android@12.0.0
4 cordova plugin add https://github.com/apache/cordova-plugin-camera.git
5 In project structure (Project) change
	gradle plugin version : 7.1.2
	gradle version :  7.5
6 In project structure (SDK Location) of Gradle Settings

	Gradle Jdk :  corretto-17

**Comment by breautek** [comment]
> git clone https://github.com/apache/cordova-plugin-camera.git

Use current release instead of the tip of master of the development branch which will be unstable. At the time of writing, there has been no commits between the current release and the master branch outside of chore commits (e.g. bumping to `7.0.1-dev` version) so if the master branch works, then so should 7.0.0.

> android:largeHeap="true" android:requestLegacyExternalStorage="true" android:usesCleartextTraffic="true"

This is overall simply bad advice

> android:largeHeap="true"

This will allow the Java heap to grow much larger than the standard 256mb the OS gives you. Garbage collection can be delayed and when GC does occur it can take a significantly longer time to accomplish leading to stuttering UI and poor app performance.

> android:requestLegacyExternalStorage="true" 

Today this is a no-op, it only applies if you're targeting API 29, and only applies if you had the app published before API 29 was released. Today, Google Play requires targeting API 33.

> android:usesCleartextTraffic="true"

This should only be used in testing/development environments. Google expects you to be using secured traffic whenever possible so that your user data is properly secured.

I've locked this thread to respect the OP's inbox, because it seems to be going off topic (e.g. we can't provide assistance if you're using a fork of this plugin). If there are issues with v7 of this plugin, I'd recommend raising a new issue with the details filled out so that it can be tracked and addressed accordingly.
