### ISSUE TITLE
Cordova 12 is released (Android 13 support)

### ISSUE THREAD

**Issue by Emanuelmoves** [apache/cordova-plugin-camera#834]
I tried 
https://github.com/apache/cordova-plugin-camera/pull/814
With cordova 12, it sadly it doesn't seem to work out of the box.

The end of that pull request thread mentions it's locked until Cordova 12 is released and it's now released. 

Maybe the experiments/comments/feedback should continue on that PR?
---

This is with ionic 5.4.16 in case it matters.

**Comment by breautek** [comment]
> Maybe the experiments/comments/feedback should continue on that PR?

Yes, the PR was blocked until cordova-android@12 saw a release as the PR required API 33 support. Now that cordova-android@12 is out, we can start resuming testing and ensuring the CI passes.

The CI as it stands looks like it's failing on android 5, which would be expected since that is no longer a supported version.
For iOS, that's been an outstanding issue and likely no related to that PR. And the chrome tests also suffers the same issue as iOS.

Testing the PR and giving your feedback would be much appreciated. If you run into issues, then please raise a new issue with the issue form filled out.

Thank you
