### ISSUE TITLE
NSLocationAlwaysAndWhenInUseUsageDescription warning whit release 6.0.0

### ISSUE THREAD

**Issue by EliaMinozzi** [apache/cordova-plugin-camera#836]
Hi,
I used this plugin to upload photos and images in my app, but when I put my IOS app on the app store they send me this mail:

""
ITMS-90738: Invalid purpose string value - The “” value for the NSLocationAlwaysAndWhenInUseUsageDescription key isn’t allowed in “MyApp.app”. Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “MyApp.app” bundle should contain a NSLocationAlwaysAndWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. For details, visit:
https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team
""

I added NSLocationAlwaysAndWhenInUseUsageDescription because apple warned me about it, however i set CameraUsesGeolocation preference to false, so I don't know what I must write in NSLocationAlwaysAndWhenInUseUsageDescription  as value.

Thank you.
Elia

**Comment by breautek** [comment]
> Invalid purpose string value - The “” value... 

I think Apple's problem is the fact that your project appears to have an empty value (rather than completely non-set).

The camera plugin does not set or attempt to set `NSLocationAlwaysAndWhenInUseUsageDescription` or any other plist property so I don't think this is a bug in this plugin.

I'd scan through your plugins `plugin.xml` files (or perhaps your own `config.xml`) file for config-file/edit-config entries for `NSLocationAlwaysAndWhenInUseUsageDescription` to see the likely culprit that might be setting the value to an empty string.
