### ISSUE TITLE
Camera or gallery doesn't open due to maxsdkversion in plugin.xml

### ISSUE THREAD

**Issue by bipin-52165** [apache/cordova-plugin-camera#894]
# Bug Report
camera or gallery doesn't open due to maxsdkversion mentioned as 32
## Problem
currently google updated their policy to use minsdkversion is 33 and when I checked in tablet with android version 9 then it doesn't open camera

### What is expected to happen?
it should open camera or gallery option

### What does actually happen?
it doesn't open camera or gallery option

## Information

 you guys need to update maxsdkversion in plugin.xml at line no. 58 by 33 or 34 otherwise it will not work in future

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
That's not right.

https://github.com/apache/cordova-plugin-camera/blob/3b73186b916c66989effffa46a26626ee0af77bd/plugin.xml#L58 is `WRITE_EXTERNAL_STORAGE` permission, which only applies to API 32 and lower. It is always rejected on API 33 and later devices.

WRITE permission itself is actually obsolete since API 29 with scoped storage mechanism, but it implicitly grants `READ_EXTERNAL_STORAGE` up to and including API 32. On API 33+, it will be auto rejected.

Starting with API 33, `READ_EXTERNAL_STORAGE` is replaced by `READ_MEDIA_IMAGES`, `READ_MEDIA_AUDIO`, and `READ_MEDIA_VIDEO`, which current latest version of this plugin uses (except for the audio permission) if running on an API 33+ environment.

Google has announced that they are going to be locking down on apps requesting the `READ_MEDIA_*` permissions if the app does not have justification for broad access to the media content. In a future release, likely in a new major release we will be removing the `READ_MEDIA` permission usage and reworking the code to use the native MediaStore APIs. You can test this change by installing the PR: https://github.com/apache/cordova-plugin-camera/pull/889

It will likely require some changes in your API consumption in your app code as it will return `content://` paths on android, which is **temporary** access. For example, if long term access is required, then a file copy operation will be required.

**Comment by bipin-52165** [comment]
It was not working before. I updated maxsdkversion by 33 and tested as well. So don't think it is working with 32
